### ISSUE TITLE
unexpected editor background color

### ISSUE THREAD

**Issue by runsisi** [precious-themes/precious-themes-intellij-platform#6]
after upraged to 232.1, backgroud color of the editor seems weird:

![image](https://github.com/precious-themes/precious-themes-intellij-platform/assets/2339258/f71c22cc-da81-4362-b78f-23c5e6eceef9)

this is the expected color from the last release:

![image](https://github.com/precious-themes/precious-themes-intellij-platform/assets/2339258/b6c0f2e2-e8e6-4a62-8b68-66772ef3ce0b)

**Comment by 4lex4** [comment]
https://www.jetbrains.com/help/idea/configuring-colors-and-fonts.html

**Comment by runsisi** [comment]
hi @4lex4 do you mean this color change in 232.1 is expected? thanks!

**Comment by runsisi** [comment]
ok, i know what u meant. after the upgrade, the editor color theme needs change explicitly. thanks!

![image](https://github.com/precious-themes/precious-themes-intellij-platform/assets/2339258/7652c0de-51e4-4763-acff-abc53366dd67)
