### ISSUE TITLE
Perhaps mention "Solarized" in the theme description

### ISSUE THREAD

**Issue by lofidevops** [precious-themes/precious-themes-intellij-platform#7]
I was confused when I couldn't find my trusty Solarized theme until I stumbled across Precious quite by accident. It would be helpful to previous users to add "Solarized" in the theme description, so that they can consider "Precious" as an alternative. Something like...

> This may appeal to users of my previous "Solarized" theme (no longer maintained).

**Comment by 4lex4** [comment]
These are completely different themes not related to solarized in any way except similarity of the warm theme background, nor it is a some replacement for solarized.  I have archived the solarized repo and just pointed out what I moved onto as the reason why the former will not be maintained, that is all.

I have created and shared the themes I am satisfied with, so use and maintain it. I will not support for free what I do not use, you do it yourself if you need it, solarized themes are the past for me.
