### ISSUE TITLE
'More Actions' icon imperceptible in the Run Widget

### ISSUE THREAD

**Issue by mfunaro** [precious-themes/precious-themes-intellij-platform#8]
Using the Precious Light Warm theme (as a Solarized light replacement), the Run Widget -> 'More Actions'
 icon is very difficult to see. 

![image](https://github.com/precious-themes/precious-themes-intellij-platform/assets/4819184/40892265-e10d-4fd0-8b84-0dceb848922d)

Other similar icons (3 vertical dots) in other widgets/areas of the IDE are very clear

![image](https://github.com/precious-themes/precious-themes-intellij-platform/assets/4819184/ef448213-b16d-4a77-a25c-e7adb45faea1)

**Comment by 4lex4** [comment]
Fixed in bed89fd
